sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install python-coveralls
  - pip install pytest
  - pip install pytest-pep8
  - pip install pytest-cov
script: py.test --pep8 --cov
after_success:
  - coveralls